### ISSUE TITLE
As user I want to observe the docker build logs of completed builds, to investigate errors

### ISSUE THREAD

**Issue by whymatter** [harbourrocks/harbour#4]
### Purpose
If a build fails the logs of the docker build command are the best and only option to observe what went wrong.

**This story is not about streaming the logs of a running build!**

### Subtasks
- [ ] Finish HiFi design
- [ ] Show logs on the detail page of build
- [ ] Figure out how to store logs
- [ ] Store logs
- [ ] GraphQL endpoint to deliver logs
- [ ] What happens with really huge logs? Like 10 MB ...
