### ISSUE TITLE
As user I want to have a detail page of a build to observe several properties

### ISSUE THREAD

**Issue by whymatter** [harbourrocks/harbour#5]
### Purpose
When a build was started there should be a detail page regarding the running and later on finished build.

This does not include the build logs, there is a separate task for this #4 

### Subtasks
- [ ] Finish HiFi design
- [ ] GraphQL endpoint to deliver status of build, commit, scm repository
- [ ] Create detail page in UI
